# Generated by Django 3.2.5 on 2021-12-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerid', models.BigIntegerField(db_column='playerID', primary_key=True, serialize=False)),
                ('name_main', models.TextField(blank=True, db_column='Name_main', null=True)),
                ('name_kana', models.TextField(blank=True, db_column='Name_kana', null=True)),
                ('team_n', models.TextField(blank=True, db_column='Team_N', null=True)),
                ('team_id', models.BigIntegerField(blank=True, db_column='Team_ID', null=True)),
                ('uni_num', models.TextField(blank=True, null=True)),
                ('posi', models.TextField(blank=True, null=True)),
                ('birthday', models.TextField(blank=True, db_column='Birthday', null=True)),
                ('birthplace', models.TextField(blank=True, db_column='Birthplace', null=True)),
                ('tall', models.TextField(blank=True, db_column='Tall', null=True)),
                ('weight', models.TextField(blank=True, db_column='Weight', null=True)),
                ('bloodtype', models.TextField(blank=True, db_column='Bloodtype', null=True)),
                ('pit_bat', models.TextField(blank=True, db_column='Pit_Bat', null=True)),
                ('draft', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('old_school', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stats2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_main', models.TextField(blank=True, db_column='Name_main', null=True)),
                ('stype', models.TextField(blank=True, db_column='Stype', null=True)),
                ('per', models.FloatField(blank=True, null=True)),
                ('pa', models.FloatField(blank=True, db_column='PA', null=True)),
                ('ab', models.FloatField(blank=True, db_column='AB', null=True)),
                ('hit', models.BigIntegerField(blank=True, null=True)),
                ('single', models.BigIntegerField(blank=True, null=True)),
                ('double', models.BigIntegerField(blank=True, null=True)),
                ('triple', models.BigIntegerField(blank=True, null=True)),
                ('homerun', models.BigIntegerField(blank=True, null=True)),
                ('tb', models.BigIntegerField(blank=True, db_column='TB', null=True)),
                ('rbi', models.FloatField(blank=True, db_column='RBI', null=True)),
                ('k', models.BigIntegerField(blank=True, db_column='K', null=True)),
                ('bb', models.FloatField(blank=True, db_column='BB', null=True)),
                ('db', models.FloatField(blank=True, db_column='DB', null=True)),
                ('sb', models.FloatField(blank=True, db_column='SB', null=True)),
                ('sf', models.FloatField(blank=True, db_column='SF', null=True)),
                ('dp', models.FloatField(blank=True, db_column='DP', null=True)),
                ('avg', models.FloatField(blank=True, db_column='AVG', null=True)),
                ('slg', models.FloatField(blank=True, db_column='SLG', null=True)),
                ('obp', models.FloatField(blank=True, db_column='OBP', null=True)),
                ('ops', models.FloatField(blank=True, db_column='OPS', null=True)),
                ('sw', models.FloatField(blank=True, db_column='Sw', null=True)),
                ('co', models.FloatField(blank=True, db_column='Co', null=True)),
                ('ssw', models.FloatField(blank=True, db_column='SSw', null=True)),
                ('sco', models.FloatField(blank=True, db_column='SCo', null=True)),
                ('bsw', models.FloatField(blank=True, db_column='BSw', null=True)),
                ('bco', models.FloatField(blank=True, db_column='BCo', null=True)),
                ('go', models.BigIntegerField(blank=True, db_column='GO', null=True)),
                ('fo', models.BigIntegerField(blank=True, db_column='FO', null=True)),
                ('ro', models.BigIntegerField(blank=True, db_column='RO', null=True)),
                ('pitcount', models.BigIntegerField(blank=True, null=True)),
                ('pperpa', models.FloatField(blank=True, db_column='PperPA', null=True)),
                ('sitnum', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stats2021',
                'managed': False,
            },
        ),
    ]
