# Generated by Django 3.2.5 on 2021-12-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(db_column='Team_ID', primary_key=True, serialize=False)),
                ('team_n', models.CharField(db_column='Team_N', max_length=20)),
                ('leagueid', models.IntegerField(db_column='LeagueID')),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
    ]
