# Generated by Django 3.2.5 on 2021-12-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2021', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('leagueid', models.IntegerField(db_column='LeagueID', primary_key=True, serialize=False)),
                ('leaguename', models.CharField(db_column='LeagueName', max_length=4)),
            ],
            options={
                'db_table': 'league',
                'managed': False,
            },
        ),
    ]
