# Generated by Django 3.2.5 on 2022-02-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerid', models.BigIntegerField(db_column='playerID', primary_key=True, serialize=False)),
                ('name_main', models.TextField(blank=True, db_column='Name_main', null=True)),
                ('name_kana', models.TextField(blank=True, db_column='Name_kana', null=True)),
                ('team_n', models.TextField(blank=True, db_column='Team_N', null=True)),
                ('team_id', models.BigIntegerField(blank=True, db_column='Team_ID', null=True)),
                ('uni_num', models.TextField(blank=True, null=True)),
                ('posi', models.TextField(blank=True, null=True)),
                ('birthday', models.TextField(blank=True, db_column='Birthday', null=True)),
                ('birthplace', models.TextField(blank=True, db_column='Birthplace', null=True)),
                ('tall', models.TextField(blank=True, db_column='Tall', null=True)),
                ('weight', models.TextField(blank=True, db_column='Weight', null=True)),
                ('bloodtype', models.TextField(blank=True, db_column='Bloodtype', null=True)),
                ('pit_bat', models.TextField(blank=True, db_column='Pit_Bat', null=True)),
                ('draft', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('old_school', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stats2021P',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('tid', models.BigIntegerField(blank=True, db_column='tID', null=True)),
                ('lid', models.BigIntegerField(blank=True, db_column='lID', null=True)),
                ('name_main', models.TextField(blank=True, db_column='Name_main', null=True)),
                ('stype', models.TextField(blank=True, db_column='Stype', null=True)),
                ('per', models.FloatField(blank=True, null=True)),
                ('bc', models.FloatField(blank=True, db_column='BC', null=True)),
                ('o', models.FloatField(blank=True, db_column='O', null=True)),
                ('hit', models.BigIntegerField(blank=True, null=True)),
                ('single', models.BigIntegerField(blank=True, null=True)),
                ('double', models.BigIntegerField(blank=True, null=True)),
                ('triple', models.BigIntegerField(blank=True, null=True)),
                ('homerun', models.BigIntegerField(blank=True, null=True)),
                ('tb', models.BigIntegerField(blank=True, db_column='TB', null=True)),
                ('r', models.FloatField(blank=True, db_column='R', null=True)),
                ('k', models.BigIntegerField(blank=True, db_column='K', null=True)),
                ('bb', models.FloatField(blank=True, db_column='BB', null=True)),
                ('db', models.FloatField(blank=True, db_column='DB', null=True)),
                ('dp', models.FloatField(blank=True, db_column='DP', null=True)),
                ('oba', models.FloatField(blank=True, db_column='OBA', null=True)),
                ('whip', models.FloatField(blank=True, db_column='WHIP', null=True)),
                ('era', models.FloatField(blank=True, db_column='ERA', null=True)),
                ('sw', models.FloatField(blank=True, db_column='Sw', null=True)),
                ('co', models.FloatField(blank=True, db_column='Co', null=True)),
                ('ssw', models.FloatField(blank=True, db_column='SSw', null=True)),
                ('sco', models.FloatField(blank=True, db_column='SCo', null=True)),
                ('bsw', models.FloatField(blank=True, db_column='BSw', null=True)),
                ('bco', models.FloatField(blank=True, db_column='BCo', null=True)),
                ('go', models.BigIntegerField(blank=True, db_column='GO', null=True)),
                ('fo', models.BigIntegerField(blank=True, db_column='FO', null=True)),
                ('ro', models.BigIntegerField(blank=True, db_column='RO', null=True)),
                ('pitcount', models.BigIntegerField(blank=True, null=True)),
                ('pperpa', models.FloatField(blank=True, db_column='PperPA', null=True)),
                ('sitnum', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stats2021p',
                'managed': False,
            },
        ),
    ]
