# Generated by Django 3.2.5 on 2021-12-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player2021', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardModel',
        ),
    ]
